defmodule AdventOfCode.Day08Test do
  use ExUnit.Case

  import AdventOfCode.Day08

  # @tag :skip
  test "part 1: 2 antennae" do
    input = """
    ..........
    ..........
    ..........
    ....a.....
    ..........
    .....a....
    ..........
    ..........
    ..........
    ..........
    """

    2 = part1(input)
  end

  # @tag :skip
  test "part 1: 3 antennae" do
    input = """
    ..........
    ..........
    ..........
    ....a.....
    ........a.
    .....a....
    ..........
    ..........
    ..........
    ..........
    """

    4 = part1(input)
  end

  # @tag :skip
  test "part1: full" do
    input = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    14 = part1(input)
  end

  @tag :skip
  test "part2" do
    input = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    result = part2(input)

    assert result
  end
end
